name: Build & Push gh-pages (ffmpeg.wasm PoC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # wichtig für Push auf gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build public/
        run: |
          set -eux
          rm -rf public
          mkdir -p public/vendor/ffmpeg/core/umd public/vendor/ffmpeg/umd
          # @ffmpeg/core (UMD js+wasm)
          CORE_TGZ="$(npm pack @ffmpeg/core@0.12.10)"
          tar -xzf "$CORE_TGZ"
          cp package/dist/umd/* public/vendor/ffmpeg/core/umd/
          rm -rf package "$CORE_TGZ"
          # @ffmpeg/ffmpeg (UMD + Chunk-Dateien)
          FFMPEG_TGZ="$(npm pack @ffmpeg/ffmpeg@0.12.15)"
          tar -xzf "$FFMPEG_TGZ"
          cp -r package/dist/umd/* public/vendor/ffmpeg/umd/
          rm -rf package "$FFMPEG_TGZ"
          # index.html + .nojekyll
          cp index.html public/index.html
          touch public/.nojekyll
          # harte Checks
          test -f public/vendor/ffmpeg/core/umd/ffmpeg-core.js
          test -f public/vendor/ffmpeg/core/umd/ffmpeg-core.wasm
          test -f public/vendor/ffmpeg/umd/ffmpeg.js

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
          force_orphan: true
