name: Build & Deploy Pages (ffmpeg.wasm PoC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  FFMPEG_VERSION: 0.12.10
  CORE_VERSION: 0.12.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch ffmpeg bundles into ./public
        run: |
          set -e
          mkdir -p public/vendor/ffmpeg/core public/vendor/ffmpeg/umd

          echo "Downloading @ffmpeg/core@${CORE_VERSION}…"
          CORE_TGZ=$(npm pack @ffmpeg/core@${CORE_VERSION})
          echo "CORE_TGZ=${CORE_TGZ}"
          tar -xzf "$CORE_TGZ"
          cp -r package/dist/* public/vendor/ffmpeg/core/
          rm -rf package "$CORE_TGZ"

          echo "Downloading @ffmpeg/ffmpeg@${FFMPEG_VERSION}…"
          FFMPEG_TGZ=$(npm pack @ffmpeg/ffmpeg@${FFMPEG_VERSION})
          echo "FFMPEG_TGZ=${FFMPEG_TGZ}"
          tar -xzf "$FFMPEG_TGZ"
          cp -r package/dist/umd/* public/vendor/ffmpeg/umd/
          rm -rf package "$FFMPEG_TGZ"

          # deine index.html in den Publish-Ordner
          cp index.html public/index.html
          # Jekyll aus
          touch public/.nojekyll

          echo "Tree under public/:"
          find public -maxdepth 3 -type f -printf "%P\n"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
